### ISSUE TITLE
Console spam everytime I break a stone block

### ISSUE THREAD

**Issue by smuggufo** [Qballl/StaffPlus#2] opened 2017-09-19 16:54 UTC
Here is the console
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]
        at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]

It will keep spamming that as long as a player is breaking stone. It really lags my server

**Comment by Qballl** [comment] 2017-09-19 18:08
Is there an error after this or before this or is this all it tells you?

**Comment by smuggufo** [comment] 2017-09-19 18:59
Could not pass event BlockBreakEvent to StaffPlus v3.2.3
org.bukkit.event.EventException: null
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins%20v1.1.0.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:883) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-65e8124-8bf06d6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.StackOverflowError
        at java.io.File.<init>(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.RegionFileCache.a(RegionFileCache.java:16) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.RegionFileCache.d(RegionFileCache.java:79) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:62) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:21) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:131) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:193) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:201) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:197) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]

**Comment by Qballl** [comment] 2017-09-19 19:39
Are you sure your world isn't corrupted at some chunk as the root cause of the error is an IOException

**Comment by smuggufo** [comment] 2017-09-19 19:40
Im dont think it is. I dont have any problems with the world. Everything works fine except when someone mines stoneblocks anywhere in the world. If it was corrupted how would i go about finding out?

**Comment by Qballl** [comment] 2017-09-19 19:47
Hmm idk I'm gonna have to get a second opinion on this error. I noticed that there is no line that mentions staffplus so does the original error come at random without this error?

**Comment by smuggufo** [comment] 2017-09-20 03:08
I never even noticed the first error before today, The "at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:81) ~[?:?]" error i posted all those lines are from breaking one stone block in survival. Usually my console is to spammed with it to scroll all the way up

**Comment by smuggufo** [comment] 2017-09-20 19:56
Also is there any way to stop it from saying in chat when a player mines stone?

**Comment by Qballl** [comment] 2017-09-20 20:00
I can disable the vein checker for now until I properly fix otherwise this could crash your server.

**Comment by Qballl** [comment] 2017-09-20 20:05
https://www.dropbox.com/s/rxjxyhj6j4ori8z/Staff%2B.jar?dl=0 Here is a version with this disabled so we wont crash servers now https://www.dropbox.com/s/rxjxyhj6j4ori8z/Staff%2B.jar?dl=0

**Comment by smuggufo** [comment] 2017-09-24 18:07
Thank you, I'll install that now and see what happens

**Comment by smuggufo** [comment] 2017-09-24 19:12
That actually really helped. The only problem now is it spams the staffs chat everytime a player mines stone which is quite alot. Any way to remove that? Its not very useful since its just stone

**Comment by Qballl** [comment] 2017-09-24 20:51
Ill remove the feature till i fix it when I get a chance

**Comment by Qballl** [comment] 2017-09-25 04:39
Alright redownload from the dropbox link

**Comment by smuggufo** [comment] 2017-09-25 04:41
Thank you good sir! Thank you for all the help, you do have an amazing plugin!

**Comment by Qballl** [comment] 2017-09-25 19:39
Here please try this https://github.com/Qballl/StaffPlus/releases/tag/3.2.4 I believe that should fix the lag that was being caused by a recursive method call techy stuff but you noticed the lag and reported it so I can not thank you enough

**Comment by smuggufo** [comment] 2017-09-26 19:53
Im only seeing the source code not the .jar but you're welcome!

**Comment by Qballl** [comment] 2017-09-26 20:10
Hmm let me look at this

**Comment by Qballl** [comment] 2017-09-26 20:11
Fixed it

**Comment by smuggufo** [comment] 2017-09-27 00:18
The console spam is back and it seems worse.
at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?]at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?]at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?]at net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91) ~[?:?

**Comment by smuggufo** [comment] 2017-09-27 00:20
[20:12:36][Spigot Watchdog Thread/ERROR]: net.shortninja.staffplus.server.listener.BlockBreak.calculateVein(BlockBreak.java:91)

**Comment by Qballl** [comment] 2017-09-27 00:44
Well this doesn't seem good

**Comment by Qballl** [comment] 2017-09-27 00:49
Revert to the old version

**Comment by smuggufo** [comment] 2017-10-09 23:44
So whats the news?

**Comment by Qballl** [comment] 2017-10-10 00:51
Not much haven't had a lot of time to work on it

**Comment by Qballl** [comment] 2017-10-16 03:58
Hey Im still working on this dont worry

**Comment by Qballl** [comment] 2018-01-16 18:08
This no longer happens correct? If I remember I just removed the feature and planned on fixing it at a latter time.

**Comment by Qballl** [comment] 2018-05-31 14:43
Im gonna close this now if it still happens you can comment on the closed issue

**Closed by Qballl** 2018-05-31 14:43 UTC
Labels: bug
