### ISSUE TITLE
NullPointerException on /staff

### ISSUE THREAD

**Issue by TheMinecraftBaws** [Qballl/StaffPlus#38] opened 2018-06-27 16:59 UTC
The title and here is the stacktrace:
> [11:56:23 INFO]: TheMinecraftBaws issued server command: /staff
> [11:56:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'staff' in net.shortninja.staffplus.server.command.cmd.mode.ModeCmd(staff)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-c3093ef-aa25568]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-c3093ef-aa25568]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-c3093ef-aa25568]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-c3093ef-aa25568]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
at net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.toggleMode(ModeCmd.java:68) ~[?:?]
at net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.execute(ModeCmd.java:60) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-c3093ef-aa25568]
... 14 more

**Comment by Qballl** [comment] 2018-06-27 18:49
Thanks for the report I will look into this

**Comment by Qballl** [comment] 2018-07-16 14:17
Well I looked into this and I am baffled at how you got this. Did you do /staff on a player that was offline or something?

**Comment by TheMinecraftBaws** [comment] 2018-07-17 10:17
Nah

**Comment by Humeur** [comment] 2018-08-02 15:48
I have the same problem.

**Comment by Humeur** [comment] 2018-08-04 16:27
Can you please resolve that...

**Comment by Qballl** [comment] 2018-08-04 21:39
What plugin version are you using?

**Comment by Damdamdu95** [comment] 2018-10-13 17:34
Same problem : https://pastebin.com/GZ2WmMHB

**Comment by Qballl** [comment] 2018-11-20 03:41
@TheMinecraftBaws I'm gonna need you to resend the error as the numbers no longer match up. My guess is that it is trying to say the player is null but that is just impossible and @Damdamdu95 your error is different

**Comment by GethelpObv** [comment] 2018-11-28 15:21
Also getting it using staff+3.2.8

`[01:17:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'staff' in net.shortninja.staffplus.server.command.cmd.mode.ModeCmd(staff)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[test.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) ~[test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1178) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:991) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [test.jar:git-TacoSpigot-bf023c7d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [test.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [test.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getExtraContents()[Lorg/bukkit/inventory/ItemStack;
	at net.shortninja.staffplus.player.attribute.mode.ModeCoordinator.addMode(ModeCoordinator.java:59) ~[?:?]
	at net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.toggleMode(ModeCmd.java:58) ~[?:?]
	at net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.execute(ModeCmd.java:49) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[test.jar:git-TacoSpigot-bf023c7d]
	... 14 more`

**Comment by Qballl** [comment] 2018-11-28 16:40
@GethelpObv your error is a different one and is already fixed in the version I'm working on currently

**Comment by xdjoe** [comment] 2018-11-28 17:44
@Qballl I have the same issue as @TheMinecraftBaws . Is there any way to fix it? ......

**Comment by Qballl** [comment] 2018-11-28 18:41
@xdjoe If you could pastebin your error that would be helpful b/c their line numbers dont match up due to some reformatting

**Comment by xdjoe** [comment] 2018-11-28 18:44
28.11 19:44:00 [Server] INFO ClickFastLickAss issued server command: /staff
28.11 19:44:00 [Server] ERROR null
28.11 19:44:00 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'staff' in net.shortninja.staffplus.server.command.cmd.mode.ModeCmd(staff)
28.11 19:44:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getExtraContents()[Lorg/bukkit/inventory/ItemStack;
28.11 19:44:00 [Server] INFO at net.shortninja.staffplus.player.attribute.mode.ModeCoordinator.addMode(ModeCoordinator.java:59) ~[?:?]
28.11 19:44:00 [Server] INFO at net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.toggleMode(ModeCmd.java:58) ~[?:?]
28.11 19:44:00 [Server] INFO at net.shortninja.staffplus.server.command.cmd.mode.ModeCmd.execute(ModeCmd.java:49) ~[?:?]
28.11 19:44:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot-1.7.10.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
28.11 19:44:00 [Server] INFO ... 12 more

@Qballl

**Comment by xdjoe** [comment] 2018-11-28 20:07
When will the update be released

**Comment by Qballl** [comment] 2018-11-28 20:40
@xdjoe Just released it. That is the last update until after my final exams on December 9th

**Comment by xdjoe** [comment] 2018-11-29 16:32
I'm still getting the exact same issue lol nice update btw

**Comment by Azoraqua** [comment] 2020-10-03 12:33
I assume it's fixed by now and therefore I'll close this issue.

**Closed by Azoraqua** 2020-10-03 12:33 UTC
Labels: error
