### ISSUE TITLE
Work with supervanish

### ISSUE THREAD

**Issue by Dream-cake** [Qballl/StaffPlus#34] opened 2018-06-16 15:02 UTC
hi! can you make it if the server has supervanish it will do that not its own or somehow add it in the config

**Comment by Qballl** [comment] 2018-06-16 21:53
I'm not sure why you would need a separate vanish if this has it own but I'll work that into the next next update the next one is already planned it close to being done

**Comment by Dream-cake** [comment] 2018-06-17 01:55
ok thanks

**Comment by Qballl** [comment] 2018-11-20 03:37
I still do not see a need for this gonna close it. Vanish from this now works as intended

**Closed by Qballl** 2018-11-20 03:37 UTC
