### ISSUE TITLE
Vanish feature while in staff mode is sometimes unable to be toggled

### ISSUE THREAD

**Issue by Jadiction** [Qballl/StaffPlus#135] opened 2020-01-22 12:58 UTC
I haven't found a pattern so as of right now it's "random", but at times the vanish toggle sends twice preventing you from enabling/disabling. 

![](https://image.prntscr.com/image/LaA59aMXShuiGJ4_M26KBg.png)

**Comment by Qballl** [comment] 2020-02-11 05:07
Duplicate of #127 closing this one

**Closed by Qballl** 2020-02-11 05:07 UTC
