### ISSUE TITLE
Request: differentiate player placed ores (blocks) for xray reporting

### ISSUE THREAD

**Issue by fahlur** [Qballl/StaffPlus#42] opened 2018-08-21 21:58 UTC
Anyway someone could put in something to differentiate the 2? its annoying to see someone mine a ton of diamonds with silk then turn around with fortune later. looks off when you see 30 messages showing in chat later on because they did such xD

**Comment by Qballl** [comment] 2018-08-21 22:54
Simple answer is yes. I would I would have to log all placed blocks of a certain type

**Comment by Azoraqua** [comment] 2019-07-07 16:00
I don't think it's beneficial for this plugin.

**Comment by fahlur** [comment] 2019-07-29 09:46
mmm i do considering the fact I get so many false positives because of this. But back during the time of me posting this request I made a fork and added the functionality it was very easy to add and took next to no time to add it. Made the results so much better

**Comment by Azoraqua** [comment] 2019-07-29 18:08
It's easy to implement, yes. But the problem is mainly that it takes a lot of memory to store those blocks especially over a lot of block changes.

It's basically calculated like this: `n * m` where n is the amount of blocks per player and m the amount of players. Which could end up with several thousands of entries in a single server.

Which would end up quickly with several megabytes or even gigabytes of memory just for a simple anti-xray feature. Thus I don't think it's beneficial. 

== I vote to close this issue because of that.

**Comment by fahlur** [comment] 2019-08-04 16:03
I.. just.. just check if they place a block if its a special ore such as diamond ore... then store that location in list... check if the block is broken against the listand if it exists in that list then say no dont increment the score and then remove the ore off that list.. The list is easily stored in a yml file as well. It takes next to nill on code. I already implemented this on my own setup. im happy to show and it works just fine.

**Comment by Azoraqua** [comment] 2019-08-04 16:22
I know how to implement it, but I don't want to implement it that way. 
Otherwise I already did.

**Comment by fahlur** [comment] 2019-08-04 16:51
Do as you wish with your end. ive had my fork implemented in this manner and have never had issues with memory build up and it cleans up well. so idk.

**Comment by Azoraqua** [comment] 2019-08-04 16:53
If you feel like it, you can make a pull-request.

**Closed** 2019-08-04 16:54 UTC
