### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by sandor111** [Qballl/StaffPlus#102] opened 2019-08-26 20:16 UTC
Spigot ver 1.13
https://pastebin.com/chgeZp4D

**Comment by Azoraqua** [comment] 2019-08-28 11:33
Alright, thanks for notifying us. We'll take a look at it.

**Comment by AigleDev** [comment] 2019-09-02 22:08
`Excessive velocity set detected: tried to set velocity of entity SteffJonez id #712340 to (2.09746196116341,-0.274793204765056,4.530468189501775).`
change the velocity in config to a lower number and should work ^^

**Comment by Azoraqua** [comment] 2020-10-03 12:52
I assume the issue is fixed and therefore I'll close this issue.

**Closed by Azoraqua** 2020-10-03 12:52 UTC
